//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.18 at 07:33:33 PM PDT 
//


package com.bgi.esm.monitoring.platform.dispatcher.ServiceCenter.ticket;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bgi.esm.portlets.EventDatabase.ticket package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bgi.esm.portlets.EventDatabase.ticket
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Recordset }
     * 
     */
    public Recordset createRecordset() {
        return new Recordset();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link ProblemSummary }
     * 
     */
    public ProblemSummary createProblemSummary() {
        return new ProblemSummary();
    }

}
