//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.18 at 07:33:33 PM PDT 
//


package com.bgi.esm.monitoring.platform.dispatcher.ServiceCenter.ticket;

import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ProblemSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProblemSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number" type="{}TicketNumber"/>
 *         &lt;element name="number.attach" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vj.number.5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vj.number.4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vj.number.3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vj.number.2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vj.number.1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="number.vj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="open.time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="opened.by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priority.code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="severity.code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="update.time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="assignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referral.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referred.to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alert.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="close.time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="closed.by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="elapsed.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vendor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reference.no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referral.to.contact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onsite.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact.to.respond" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="repair.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onsite.to.repair" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backup.start" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backup.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backup.end" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="downtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cause.code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resolution.code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logical.name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logical.name.vj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="job.name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abend.code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="action" type="{}Action"/>
 *         &lt;element name="resolution" type="{}Action"/>
 *         &lt;element name="affected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="key.words" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xreference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alert1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alert2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alert3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deadline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reassigned" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lookup.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="total.pages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="downtime.end" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="downtime.start" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assignee.name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="respond.time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact.name" type="{}CustomerId"/>
 *         &lt;element name="contact.name.vj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seconds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caller.id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contact.phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="update.action" type="{}Action"/>
 *         &lt;element name="actor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="asgnchg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="respond.to.onsite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="network.name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="final.close" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="open.group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alert.status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deadline.group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deadline.alert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pending.date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referral.count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pending.reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="network.address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outage.type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="callback.list" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="closing.comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cs.code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProblemSummary", propOrder = {
    "number",
    "numberAttach",
    "vjNumber5",
    "vjNumber4",
    "vjNumber3",
    "vjNumber2",
    "vjNumber1",
    "numberVj",
    "category",
    "openTime",
    "openedBy",
    "priorityCode",
    "severityCode",
    "updateTime",
    "assignment",
    "referralTime",
    "referredTo",
    "alertTime",
    "status",
    "closeTime",
    "closedBy",
    "elapsedTime",
    "vendor",
    "referenceNo",
    "contactTime",
    "referralToContact",
    "onsiteTime",
    "contactToRespond",
    "repairTime",
    "onsiteToRepair",
    "backupStart",
    "backupTime",
    "backupEnd",
    "downtime",
    "causeCode",
    "resolutionCode",
    "logicalName",
    "logicalNameVj",
    "group",
    "jobName",
    "location",
    "version",
    "type",
    "abendCode",
    "model",
    "action",
    "resolution",
    "affected",
    "keyWords",
    "xreference",
    "alert1",
    "alert2",
    "alert3",
    "deadline",
    "reassigned",
    "id",
    "lookupTime",
    "totalPages",
    "flag",
    "downtimeEnd",
    "downtimeStart",
    "assigneeName",
    "respondTime",
    "contactName",
    "contactNameVj",
    "seconds",
    "callerId",
    "contactPhone",
    "updateAction",
    "actor",
    "format",
    "count",
    "asgnchg",
    "respondToOnsite",
    "networkName",
    "finalClose",
    "openGroup",
    "alertStatus",
    "deadlineGroup",
    "deadlineAlert",
    "pendingDate",
    "referralCount",
    "pendingReason",
    "networkAddress",
    "outageType",
    "parent",
    "domain",
    "callbackList",
    "closingComments",
    "csCode"
})
public class ProblemSummary {

    @XmlElement(required = true)
    protected String number;
    @XmlElement(name = "number.attach", required = true)
    protected String numberAttach;
    @XmlElement(name = "vj.number.5", required = true)
    protected String vjNumber5;
    @XmlElement(name = "vj.number.4", required = true)
    protected String vjNumber4;
    @XmlElement(name = "vj.number.3", required = true)
    protected String vjNumber3;
    @XmlElement(name = "vj.number.2", required = true)
    protected String vjNumber2;
    @XmlElement(name = "vj.number.1", required = true)
    protected String vjNumber1;
    @XmlElement(name = "number.vj", required = true)
    protected String numberVj;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(name = "open.time", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Calendar openTime;
    @XmlElement(name = "opened.by", required = true)
    protected String openedBy;
    @XmlElement(name = "priority.code", required = true)
    protected String priorityCode;
    @XmlElement(name = "severity.code", required = true)
    protected String severityCode;
    @XmlElement(name = "update.time", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Calendar updateTime;
    @XmlElement(required = true)
    protected String assignment;
    @XmlElement(name = "referral.time", required = true)
    protected String referralTime;
    @XmlElement(name = "referred.to", required = true)
    protected String referredTo;
    @XmlElement(name = "alert.time", required = true)
    protected String alertTime;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "close.time", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Calendar closeTime;
    @XmlElement(name = "closed.by", required = true)
    protected String closedBy;
    @XmlElement(name = "elapsed.time", required = true)
    protected String elapsedTime;
    @XmlElement(required = true)
    protected String vendor;
    @XmlElement(name = "reference.no", required = true)
    protected String referenceNo;
    @XmlElement(name = "contact.time", required = true)
    protected String contactTime;
    @XmlElement(name = "referral.to.contact", required = true)
    protected String referralToContact;
    @XmlElement(name = "onsite.time", required = true)
    protected String onsiteTime;
    @XmlElement(name = "contact.to.respond", required = true)
    protected String contactToRespond;
    @XmlElement(name = "repair.time", required = true)
    protected String repairTime;
    @XmlElement(name = "onsite.to.repair", required = true)
    protected String onsiteToRepair;
    @XmlElement(name = "backup.start", required = true)
    protected String backupStart;
    @XmlElement(name = "backup.time", required = true)
    protected String backupTime;
    @XmlElement(name = "backup.end", required = true)
    protected String backupEnd;
    @XmlElement(required = true)
    protected String downtime;
    @XmlElement(name = "cause.code", required = true)
    protected String causeCode;
    @XmlElement(name = "resolution.code", required = true)
    protected String resolutionCode;
    @XmlElement(name = "logical.name", required = true)
    protected String logicalName;
    @XmlElement(name = "logical.name.vj", required = true)
    protected String logicalNameVj;
    @XmlElement(required = true)
    protected String group;
    @XmlElement(name = "job.name", required = true)
    protected String jobName;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(name = "abend.code", required = true)
    protected String abendCode;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected Action action;
    @XmlElement(required = true)
    protected Action resolution;
    @XmlElement(required = true)
    protected String affected;
    @XmlElement(name = "key.words", required = true)
    protected String keyWords;
    @XmlElement(required = true)
    protected String xreference;
    @XmlElement(required = true)
    protected String alert1;
    @XmlElement(required = true)
    protected String alert2;
    @XmlElement(required = true)
    protected String alert3;
    @XmlElement(required = true)
    protected String deadline;
    @XmlElement(required = true)
    protected String reassigned;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "lookup.time", required = true)
    protected String lookupTime;
    @XmlElement(name = "total.pages", required = true)
    protected String totalPages;
    protected boolean flag;
    @XmlElement(name = "downtime.end", required = true)
    protected String downtimeEnd;
    @XmlElement(name = "downtime.start", required = true)
    protected String downtimeStart;
    @XmlElement(name = "assignee.name", required = true)
    protected String assigneeName;
    @XmlElement(name = "respond.time", required = true)
    protected String respondTime;
    @XmlElement(name = "contact.name", required = true)
    protected String contactName;
    @XmlElement(name = "contact.name.vj", required = true)
    protected String contactNameVj;
    @XmlElement(required = true)
    protected String seconds;
    @XmlElement(name = "caller.id", required = true)
    protected String callerId;
    @XmlElement(name = "contact.phone", required = true)
    protected String contactPhone;
    @XmlElement(name = "update.action", required = true)
    protected Action updateAction;
    @XmlElement(required = true)
    protected String actor;
    @XmlElement(required = true)
    protected String format;
    @XmlElement(required = true)
    protected String count;
    @XmlElement(required = true)
    protected String asgnchg;
    @XmlElement(name = "respond.to.onsite", required = true)
    protected String respondToOnsite;
    @XmlElement(name = "network.name", required = true)
    protected String networkName;
    @XmlElement(name = "final.close", required = true)
    protected String finalClose;
    @XmlElement(name = "open.group", required = true)
    protected String openGroup;
    @XmlElement(name = "alert.status", required = true)
    protected String alertStatus;
    @XmlElement(name = "deadline.group", required = true)
    protected String deadlineGroup;
    @XmlElement(name = "deadline.alert", required = true)
    protected String deadlineAlert;
    @XmlElement(name = "pending.date", required = true)
    protected String pendingDate;
    @XmlElement(name = "referral.count", required = true)
    protected String referralCount;
    @XmlElement(name = "pending.reason", required = true)
    protected String pendingReason;
    @XmlElement(name = "network.address", required = true)
    protected String networkAddress;
    @XmlElement(name = "outage.type", required = true)
    protected String outageType;
    @XmlElement(required = true)
    protected String parent;
    @XmlElement(required = true)
    protected String domain;
    @XmlElement(name = "callback.list", required = true)
    protected String callbackList;
    @XmlElement(name = "closing.comments", required = true)
    protected String closingComments;
    @XmlElement(name = "cs.code", required = true)
    protected String csCode;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the numberAttach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberAttach() {
        return numberAttach;
    }

    /**
     * Sets the value of the numberAttach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberAttach(String value) {
        this.numberAttach = value;
    }

    /**
     * Gets the value of the vjNumber5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjNumber5() {
        return vjNumber5;
    }

    /**
     * Sets the value of the vjNumber5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjNumber5(String value) {
        this.vjNumber5 = value;
    }

    /**
     * Gets the value of the vjNumber4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjNumber4() {
        return vjNumber4;
    }

    /**
     * Sets the value of the vjNumber4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjNumber4(String value) {
        this.vjNumber4 = value;
    }

    /**
     * Gets the value of the vjNumber3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjNumber3() {
        return vjNumber3;
    }

    /**
     * Sets the value of the vjNumber3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjNumber3(String value) {
        this.vjNumber3 = value;
    }

    /**
     * Gets the value of the vjNumber2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjNumber2() {
        return vjNumber2;
    }

    /**
     * Sets the value of the vjNumber2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjNumber2(String value) {
        this.vjNumber2 = value;
    }

    /**
     * Gets the value of the vjNumber1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjNumber1() {
        return vjNumber1;
    }

    /**
     * Sets the value of the vjNumber1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjNumber1(String value) {
        this.vjNumber1 = value;
    }

    /**
     * Gets the value of the numberVj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberVj() {
        return numberVj;
    }

    /**
     * Sets the value of the numberVj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberVj(String value) {
        this.numberVj = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the openTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getOpenTime() {
        return openTime;
    }

    /**
     * Sets the value of the openTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenTime(Calendar value) {
        this.openTime = value;
    }

    /**
     * Gets the value of the openedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenedBy() {
        return openedBy;
    }

    /**
     * Sets the value of the openedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenedBy(String value) {
        this.openedBy = value;
    }

    /**
     * Gets the value of the priorityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityCode() {
        return priorityCode;
    }

    /**
     * Sets the value of the priorityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityCode(String value) {
        this.priorityCode = value;
    }

    /**
     * Gets the value of the severityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverityCode() {
        return severityCode;
    }

    /**
     * Sets the value of the severityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverityCode(String value) {
        this.severityCode = value;
    }

    /**
     * Gets the value of the updateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets the value of the updateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateTime(Calendar value) {
        this.updateTime = value;
    }

    /**
     * Gets the value of the assignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignment() {
        return assignment;
    }

    /**
     * Sets the value of the assignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignment(String value) {
        this.assignment = value;
    }

    /**
     * Gets the value of the referralTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralTime() {
        return referralTime;
    }

    /**
     * Sets the value of the referralTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralTime(String value) {
        this.referralTime = value;
    }

    /**
     * Gets the value of the referredTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferredTo() {
        return referredTo;
    }

    /**
     * Sets the value of the referredTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferredTo(String value) {
        this.referredTo = value;
    }

    /**
     * Gets the value of the alertTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertTime() {
        return alertTime;
    }

    /**
     * Sets the value of the alertTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertTime(String value) {
        this.alertTime = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the closeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getCloseTime() {
        return closeTime;
    }

    /**
     * Sets the value of the closeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseTime(Calendar value) {
        this.closeTime = value;
    }

    /**
     * Gets the value of the closedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosedBy() {
        return closedBy;
    }

    /**
     * Sets the value of the closedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedBy(String value) {
        this.closedBy = value;
    }

    /**
     * Gets the value of the elapsedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElapsedTime() {
        return elapsedTime;
    }

    /**
     * Sets the value of the elapsedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElapsedTime(String value) {
        this.elapsedTime = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendor(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the referenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNo() {
        return referenceNo;
    }

    /**
     * Sets the value of the referenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNo(String value) {
        this.referenceNo = value;
    }

    /**
     * Gets the value of the contactTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactTime() {
        return contactTime;
    }

    /**
     * Sets the value of the contactTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactTime(String value) {
        this.contactTime = value;
    }

    /**
     * Gets the value of the referralToContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralToContact() {
        return referralToContact;
    }

    /**
     * Sets the value of the referralToContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralToContact(String value) {
        this.referralToContact = value;
    }

    /**
     * Gets the value of the onsiteTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnsiteTime() {
        return onsiteTime;
    }

    /**
     * Sets the value of the onsiteTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnsiteTime(String value) {
        this.onsiteTime = value;
    }

    /**
     * Gets the value of the contactToRespond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactToRespond() {
        return contactToRespond;
    }

    /**
     * Sets the value of the contactToRespond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactToRespond(String value) {
        this.contactToRespond = value;
    }

    /**
     * Gets the value of the repairTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairTime() {
        return repairTime;
    }

    /**
     * Sets the value of the repairTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairTime(String value) {
        this.repairTime = value;
    }

    /**
     * Gets the value of the onsiteToRepair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnsiteToRepair() {
        return onsiteToRepair;
    }

    /**
     * Sets the value of the onsiteToRepair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnsiteToRepair(String value) {
        this.onsiteToRepair = value;
    }

    /**
     * Gets the value of the backupStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupStart() {
        return backupStart;
    }

    /**
     * Sets the value of the backupStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupStart(String value) {
        this.backupStart = value;
    }

    /**
     * Gets the value of the backupTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTime() {
        return backupTime;
    }

    /**
     * Sets the value of the backupTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTime(String value) {
        this.backupTime = value;
    }

    /**
     * Gets the value of the backupEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupEnd() {
        return backupEnd;
    }

    /**
     * Sets the value of the backupEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupEnd(String value) {
        this.backupEnd = value;
    }

    /**
     * Gets the value of the downtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDowntime() {
        return downtime;
    }

    /**
     * Sets the value of the downtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDowntime(String value) {
        this.downtime = value;
    }

    /**
     * Gets the value of the causeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCauseCode() {
        return causeCode;
    }

    /**
     * Sets the value of the causeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseCode(String value) {
        this.causeCode = value;
    }

    /**
     * Gets the value of the resolutionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolutionCode() {
        return resolutionCode;
    }

    /**
     * Sets the value of the resolutionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolutionCode(String value) {
        this.resolutionCode = value;
    }

    /**
     * Gets the value of the logicalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalName() {
        return logicalName;
    }

    /**
     * Sets the value of the logicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalName(String value) {
        this.logicalName = value;
    }

    /**
     * Gets the value of the logicalNameVj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalNameVj() {
        return logicalNameVj;
    }

    /**
     * Sets the value of the logicalNameVj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalNameVj(String value) {
        this.logicalNameVj = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the abendCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbendCode() {
        return abendCode;
    }

    /**
     * Sets the value of the abendCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbendCode(String value) {
        this.abendCode = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setAction(Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setResolution(Action value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the affected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffected() {
        return affected;
    }

    /**
     * Sets the value of the affected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffected(String value) {
        this.affected = value;
    }

    /**
     * Gets the value of the keyWords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * Sets the value of the keyWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyWords(String value) {
        this.keyWords = value;
    }

    /**
     * Gets the value of the xreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXreference() {
        return xreference;
    }

    /**
     * Sets the value of the xreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXreference(String value) {
        this.xreference = value;
    }

    /**
     * Gets the value of the alert1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlert1() {
        return alert1;
    }

    /**
     * Sets the value of the alert1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlert1(String value) {
        this.alert1 = value;
    }

    /**
     * Gets the value of the alert2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlert2() {
        return alert2;
    }

    /**
     * Sets the value of the alert2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlert2(String value) {
        this.alert2 = value;
    }

    /**
     * Gets the value of the alert3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlert3() {
        return alert3;
    }

    /**
     * Sets the value of the alert3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlert3(String value) {
        this.alert3 = value;
    }

    /**
     * Gets the value of the deadline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * Sets the value of the deadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadline(String value) {
        this.deadline = value;
    }

    /**
     * Gets the value of the reassigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReassigned() {
        return reassigned;
    }

    /**
     * Sets the value of the reassigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReassigned(String value) {
        this.reassigned = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lookupTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLookupTime() {
        return lookupTime;
    }

    /**
     * Sets the value of the lookupTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLookupTime(String value) {
        this.lookupTime = value;
    }

    /**
     * Gets the value of the totalPages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPages() {
        return totalPages;
    }

    /**
     * Sets the value of the totalPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPages(String value) {
        this.totalPages = value;
    }

    /**
     * Gets the value of the flag property.
     * 
     */
    public boolean isFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     */
    public void setFlag(boolean value) {
        this.flag = value;
    }

    /**
     * Gets the value of the downtimeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDowntimeEnd() {
        return downtimeEnd;
    }

    /**
     * Sets the value of the downtimeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDowntimeEnd(String value) {
        this.downtimeEnd = value;
    }

    /**
     * Gets the value of the downtimeStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDowntimeStart() {
        return downtimeStart;
    }

    /**
     * Sets the value of the downtimeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDowntimeStart(String value) {
        this.downtimeStart = value;
    }

    /**
     * Gets the value of the assigneeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigneeName() {
        return assigneeName;
    }

    /**
     * Sets the value of the assigneeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigneeName(String value) {
        this.assigneeName = value;
    }

    /**
     * Gets the value of the respondTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespondTime() {
        return respondTime;
    }

    /**
     * Sets the value of the respondTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespondTime(String value) {
        this.respondTime = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the contactNameVj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactNameVj() {
        return contactNameVj;
    }

    /**
     * Sets the value of the contactNameVj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactNameVj(String value) {
        this.contactNameVj = value;
    }

    /**
     * Gets the value of the seconds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeconds() {
        return seconds;
    }

    /**
     * Sets the value of the seconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeconds(String value) {
        this.seconds = value;
    }

    /**
     * Gets the value of the callerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerId() {
        return callerId;
    }

    /**
     * Sets the value of the callerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerId(String value) {
        this.callerId = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the updateAction property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getUpdateAction() {
        return updateAction;
    }

    /**
     * Sets the value of the updateAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setUpdateAction(Action value) {
        this.updateAction = value;
    }

    /**
     * Gets the value of the actor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActor() {
        return actor;
    }

    /**
     * Sets the value of the actor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActor(String value) {
        this.actor = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the asgnchg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsgnchg() {
        return asgnchg;
    }

    /**
     * Sets the value of the asgnchg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsgnchg(String value) {
        this.asgnchg = value;
    }

    /**
     * Gets the value of the respondToOnsite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespondToOnsite() {
        return respondToOnsite;
    }

    /**
     * Sets the value of the respondToOnsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespondToOnsite(String value) {
        this.respondToOnsite = value;
    }

    /**
     * Gets the value of the networkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkName() {
        return networkName;
    }

    /**
     * Sets the value of the networkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkName(String value) {
        this.networkName = value;
    }

    /**
     * Gets the value of the finalClose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalClose() {
        return finalClose;
    }

    /**
     * Sets the value of the finalClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalClose(String value) {
        this.finalClose = value;
    }

    /**
     * Gets the value of the openGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenGroup() {
        return openGroup;
    }

    /**
     * Sets the value of the openGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenGroup(String value) {
        this.openGroup = value;
    }

    /**
     * Gets the value of the alertStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertStatus() {
        return alertStatus;
    }

    /**
     * Sets the value of the alertStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertStatus(String value) {
        this.alertStatus = value;
    }

    /**
     * Gets the value of the deadlineGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadlineGroup() {
        return deadlineGroup;
    }

    /**
     * Sets the value of the deadlineGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadlineGroup(String value) {
        this.deadlineGroup = value;
    }

    /**
     * Gets the value of the deadlineAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadlineAlert() {
        return deadlineAlert;
    }

    /**
     * Sets the value of the deadlineAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadlineAlert(String value) {
        this.deadlineAlert = value;
    }

    /**
     * Gets the value of the pendingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingDate() {
        return pendingDate;
    }

    /**
     * Sets the value of the pendingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingDate(String value) {
        this.pendingDate = value;
    }

    /**
     * Gets the value of the referralCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralCount() {
        return referralCount;
    }

    /**
     * Sets the value of the referralCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralCount(String value) {
        this.referralCount = value;
    }

    /**
     * Gets the value of the pendingReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingReason() {
        return pendingReason;
    }

    /**
     * Sets the value of the pendingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingReason(String value) {
        this.pendingReason = value;
    }

    /**
     * Gets the value of the networkAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkAddress() {
        return networkAddress;
    }

    /**
     * Sets the value of the networkAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkAddress(String value) {
        this.networkAddress = value;
    }

    /**
     * Gets the value of the outageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutageType() {
        return outageType;
    }

    /**
     * Sets the value of the outageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutageType(String value) {
        this.outageType = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the callbackList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallbackList() {
        return callbackList;
    }

    /**
     * Sets the value of the callbackList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallbackList(String value) {
        this.callbackList = value;
    }

    /**
     * Gets the value of the closingComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosingComments() {
        return closingComments;
    }

    /**
     * Sets the value of the closingComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosingComments(String value) {
        this.closingComments = value;
    }

    /**
     * Gets the value of the csCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsCode() {
        return csCode;
    }

    /**
     * Sets the value of the csCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsCode(String value) {
        this.csCode = value;
    }

}
