//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.18 at 07:33:33 PM PDT 
//


package com.bgi.esm.monitoring.platform.dispatcher.ServiceCenter.ticket;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="probsummary" type="{}ProblemSummary" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="_count" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="_countFound" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="_more" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="_start" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "probsummary"
})
@XmlRootElement(name = "recordset")
public class Recordset {

    protected ProblemSummary probsummary;
    @XmlAttribute(name = "_count")
    protected Integer count;
    @XmlAttribute(name = "_countFound", required = true)
    protected int countFound;
    @XmlAttribute(name = "_more")
    protected Integer more;
    @XmlAttribute(name = "_start")
    protected Integer start;

    /**
     * Gets the value of the probsummary property.
     * 
     * @return
     *     possible object is
     *     {@link ProblemSummary }
     *     
     */
    public ProblemSummary getProbsummary() {
        return probsummary;
    }

    /**
     * Sets the value of the probsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProblemSummary }
     *     
     */
    public void setProbsummary(ProblemSummary value) {
        this.probsummary = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

    /**
     * Gets the value of the countFound property.
     * 
     */
    public int getCountFound() {
        return countFound;
    }

    /**
     * Sets the value of the countFound property.
     * 
     */
    public void setCountFound(int value) {
        this.countFound = value;
    }

    /**
     * Gets the value of the more property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMore() {
        return more;
    }

    /**
     * Sets the value of the more property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMore(Integer value) {
        this.more = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStart(Integer value) {
        this.start = value;
    }

}
