create table service_center (
  row_id varchar(63) primary key,
  message_id varchar(63),
  incident_id bigint,
  time_stamp datetime not null default current_timestamp,
  ticket_num varchar(63) not null,
  ticket_category varchar(63) not null,
  ticket_open_time varchar(63) not null,
  ticket_opened_by varchar(63) not null,
  ticket_priority_code varchar(63) not null,
  ticket_severity_code varchar(63) not null,
  ticket_update_time varchar(63) not null,
  ticket_assignment varchar(63) not null,
  ticket_alert_time varchar(63) not null,
  ticket_status varchar(63) not null,
  ticket_close_time varchar(63) not null,
  ticket_closed_by varchar(63) not null,
  ticket_flag varchar(63) not null,
  ticket_assignee_name varchar(63) not null,
  ticket_respond_time varchar(63) not null,
  ticket_contact_name varchar(63) not null,
  ticket_actor varchar(63) not null,
  ticket_format varchar(63) not null,
  ticket_deadline_group varchar(63) not null,
  ticket_deadline_alert varchar(63) not null,
  ticket_product varchar(63) not null,
  ticket_problem varchar(63) not null,
  ticket_location varchar(63) not null,
  ticket_message text not null,
  ticket_sub_category varchar(63) not null,
  message_key text not null,
  num_attempts bigint default 0
)

create table service_center_buffer (
  row_id varchar(63) primary key,
  message_id varchar(63),
  incident_id bigint,
  time_stamp datetime not null default current_timestamp,
  ticket_num varchar(63) not null,
  ticket_category varchar(63) not null,
  ticket_open_time varchar(63) not null,
  ticket_opened_by varchar(63) not null,
  ticket_priority_code varchar(63) not null,
  ticket_severity_code varchar(63) not null,
  ticket_update_time varchar(63) not null,
  ticket_assignment varchar(63) not null,
  ticket_alert_time varchar(63) not null,
  ticket_status varchar(63) not null,
  ticket_close_time varchar(63) not null,
  ticket_closed_by varchar(63) not null,
  ticket_flag varchar(63) not null,
  ticket_assignee_name varchar(63) not null,
  ticket_respond_time varchar(63) not null,
  ticket_contact_name varchar(63) not null,
  ticket_actor varchar(63) not null,
  ticket_format varchar(63) not null,
  ticket_deadline_group varchar(63) not null,
  ticket_deadline_alert varchar(63) not null,
  ticket_product varchar(63) not null,
  ticket_problem varchar(63) not null,
  ticket_location varchar(63) not null,
  ticket_message text not null,
  ticket_sub_category varchar(63) not null,
  message_key text not null,
  num_attempts bigint default 0
)

